sudo: required

language: node_js
node_js:
  - "4.2"

services:
  - docker

before_install:
  - docker pull tomlau10/sandbox-run

script:
  - docker run --rm --net none --security-opt apparmor:unconfined --entrypoint sh tomlau10/sandbox-run ls
