sudo: required

language: node_js
node_js:
  - "4.2"

services:
  - docker

before_install:
  - docker pull tomlau10/sandbox-run
  - docker pull ubuntu

script:
  - docker ps -a
  - docker run ubuntu ls
