sudo: required

dist: trusty

language: node_js
node_js:
  - "4.2"

services:
  - docker

before_install:
  - docker pull tomlau10/sandbox-run
  - docker pull ubuntu
  - docker ps -a
  - docker --version

script:
  - docker run ubuntu ls
  - docker run --rm --net=none --entrypoint=sh ubuntu -c "ls /"
  - docker run --rm --net=none --entrypoint=sh tomlau10/sandbox-run -c "ls /"
  - docker run --rm --net=none --security-opt=label:level:s0:c100,c200 --entrypoint=sh ubuntu -c "ls /"
  - docker run --rm --net=none --security-opt=apparmor:unconfined --entrypoint=sh ubuntu -c "ls /"
  - docker run --rm --net=none --security-opt=apparmor:unconfined --entrypoint=sh tomlau10/sandbox-run -c "ls /"

notifications:
  email: false
