sudo: required

dist: trusty

language: node_js
node_js:
  - "4.2"

services:
  - docker

before_install:
  - docker pull tomlau10/sandbox-run
  - docker pull ubuntu
  - docker ps -a
  - docker --version
  - id -u
  - id -g

script:
  - docker run ubuntu ls

notifications:
  email: false
