version: '3'
services:
  travis:
    image: skandyla/travis-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: /bin/sh
    command: -c 'while sleep 3600; do :; done'
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    logging:
      driver: none
  mongo:
    image: mongo:3
    ports:
      - "27018:27017"
    volumes:
      - ./volumes/mongo:/data/db
    logging:
      driver: none
  node:
    image: node:8
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity
